[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ERC-100"
authors = [{name = "ERC-100 Foundation", email = "contact@erc100.com"}]
dynamic = ["version", "description"]
